### ISSUE TITLE
Must click a number of times

### ISSUE THREAD

**Issue by abrambailey** [HangYang/one-click-extensions-manager#23] opened 2018-02-20 17:54 UTC
I usually have to click multiple times before I am finally able to see and manipulate my extensions using this plugin. Chrome Version 64.0.3282.167 (Official Build) (64-bit) on MacOS 10.13.3 (17D47).

![image](https://user-images.githubusercontent.com/978462/36440151-a1f11a5a-1634-11e8-8d96-a8c233491539.png)

**Comment by bfred-it** [comment] 2018-02-20 18:13
Yeah this is an annoying Chrome bug, for some reason the popup height is not updated most of the time. I work around it by just typing something so the list shortens and the height is updated.

**Comment by abrambailey** [comment] 2018-02-20 18:26
The typing trick doesn't seem to work on my end. Using two other extensions currently, Ghostery and Web Developer, that work in a popup. Here's the source on Web Developer https://github.com/chrispederick/web-developer/

**Comment by bfred-it** [comment] 2018-02-20 19:06
Right, but they don't populate a list. This is a [known Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=428044)

**Comment by abrambailey** [comment] 2018-02-20 19:17
Haha, just like everything Google. Super old bug with no solution.

**Comment by abrambailey** [comment] 2018-02-20 19:19
Wondering if there is some way you can get the top part of the list to display in the popup... For me it shows some part of the list way down the list, and I can't even scroll up to the top to see the search bar.

**Comment by abrambailey** [comment] 2018-02-20 19:20
Maybe start at 100% height and shrink accordingly? Then apply a opacity adjustment? I have no idea what I'm talking about of course. I don't build chrome extensions.

**Comment by bfred-it** [comment] 2018-02-20 19:38
It can probably be fixed by hiding and showing the content when `window.innerHeight` is lower than the height of the content.

**Comment by HangYang** [comment] 2018-02-22 15:25
wow, I've never notices this bug on Mac OS. Can we set a default height to the popup and then expand/shrink it to the height of the content?

**Comment by bfred-it** [comment] 2018-02-22 15:41
Any pre-set height would be too small or too high for most, so if we have to re-adjust it we might as well just do that without pre-setting any height.

**Comment by HangYang** [comment] 2018-02-22 16:01
well, I think the reason that it needs to click several times to show the popup correctly is because it does not have a default height. so Chrome will show it as a minimal height (which is the static content height of the extension window, like the search input, the 2 buttons and the message).
so we give `body` a min-height or static height (my idea is the max height of the popup window ). Chrome will show the window in this height. and then we can shrink it with an animation. 
Tested with a min-width and the bug is gone.

**Comment by bfred-it** [comment] 2018-02-22 16:12
This bug only happens a few times, we shouldn't degrade the experience for all the other times. There is no advantage in setting a min-height if you still have to detect it and fix it via JS.

**Comment by HangYang** [comment] 2018-02-22 16:23
Good point

**Comment by abrambailey** [comment] 2018-02-22 16:40
@bfred-it I would think MacOS + Chrome is a fairly common user environment for this extension. Is it possible to install a forked version of a chrome extension, or does the extension need to be in the chrome app store or whatever.

**Comment by abrambailey** [comment] 2018-03-08 18:07
You guys should probably log the click rate on this to see how widespread the issue is. Or maybe look at your install base by OS and Browser... I just clicked on it like 20 times and can't even make it stay open. I really really like this extension, and wish it worked :/

**Comment by bfred-it** [comment] 2018-03-08 18:25
I know it's a bug, that's why this issue is open. PRs welcome to fix it as instructed

**Comment by abrambailey** [comment] 2018-03-08 18:29
Sorry, I guess it's out of my comfort zone, so can't really fix it myself. I would if I could... All the other extensions like yours ask for permissions that I'm not comfortable with, which defeats the purpose of managing extension access to my browsing activity with a plugin like yours. So, I feel like this is my only choice! Anyway, I'll shut up and wait. Thanks.

**Comment by HangYang** [comment] 2018-03-09 02:09
Ah, I reproduce this issue on a iMac btw, Will look into it when I have some time.

**Comment by bfred-it** [comment] 2019-02-14 02:40
Is this still happening? I haven't seen it in a while

**Comment by abrambailey** [comment] 2019-02-14 02:49
Hasn't been an issue for me.

**Closed** 2019-02-14 02:52 UTC
Labels: bug
